### ISSUE TITLE
React.Fragment Error

### ISSUE THREAD

**Issue by sambbaron** [dlindahl/gatsby-plugin-react-a11y#3]
I am getting the following error using gatsby-plugin-react-a11y with components that use React.Fragment:

> Warning: Invalid prop `id` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.

I am using GatsbyJS v2

**Comment by dlindahl** [comment]
This is an issue in reactjs/react-a11y itseld. I would recommend opening an issue there.
